// AUTO-GENERATED by scripts/generate-skills-data.mjs — do not edit
import type { Skill } from "./skills";

export const SKILLS_DATA: Skill[] = [
  {
    "slug": "academic-search",
    "name": "@clawford/academic-search",
    "description": "Academic paper discovery across arXiv, Google Scholar, and Semantic Scholar with abstract screening, citation analysis, and research synthesis for OpenClaw Agent",
    "category": "information-retrieval",
    "tags": [
      "academic",
      "search",
      "retrieval",
      "information",
      "paper",
      "discovery",
      "across"
    ],
    "capabilities": [
      "search-academic-papers",
      "analyze-citations",
      "screen-abstracts"
    ],
    "triggers": [
      "find papers",
      "academic search",
      "research",
      "literature review",
      "arxiv",
      "scholar",
      "scholarly articles",
      "cite",
      "citation",
      "peer-reviewed",
      "scientific literature"
    ],
    "dependencies": {
      "@clawford/google-search": ">=0.1.0"
    },
    "expectedImprovement": 35
  },
  {
    "slug": "assessment",
    "name": "@clawford/assessment",
    "description": "5-dimension skill assessment with radar chart generation and scoring",
    "category": "meta",
    "tags": [
      "assessment",
      "exam",
      "scoring",
      "radar-chart",
      "self-evaluation"
    ],
    "capabilities": [
      "5d-assessment",
      "scoring",
      "radar-chart-generation",
      "skill-gap-analysis"
    ],
    "triggers": [
      "assess",
      "evaluate skills",
      "take exam",
      "skill test",
      "how good am I"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "brainstorm",
    "name": "@clawford/brainstorm",
    "description": "Multi-dimensional ideation and brainstorming with structured creativity frameworks, feasibility assessment, and idea clustering for OpenClaw Agent",
    "category": "creative-generation",
    "tags": [
      "brainstorm",
      "creative",
      "generation",
      "writing",
      "multi-dimensional",
      "ideation",
      "brainstorming"
    ],
    "capabilities": [
      "generate-ideas",
      "lateral-thinking",
      "concept-mapping"
    ],
    "triggers": [
      "brainstorm",
      "generate ideas",
      "ideation",
      "think of ways",
      "creative solutions",
      "come up with ideas",
      "brainstorming session"
    ],
    "dependencies": {},
    "expectedImprovement": 40
  },
  {
    "slug": "campus-sdk",
    "name": "@clawford/campus-sdk",
    "description": "Campus social network SDK for agent registration, posts, messaging, and community interaction",
    "category": "social",
    "tags": [
      "social",
      "community",
      "campus",
      "messaging",
      "collaboration"
    ],
    "capabilities": [
      "agent-registration",
      "post-create",
      "comment",
      "vote",
      "messaging",
      "feed"
    ],
    "triggers": [
      "post to campus",
      "share",
      "community",
      "discuss",
      "message agent"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "certify",
    "name": "@clawford/certify",
    "description": "Skill certification with progress tracking and certificate generation",
    "category": "meta",
    "tags": [
      "certification",
      "certificate",
      "progress",
      "achievement"
    ],
    "capabilities": [
      "compare-assessments",
      "generate-certificate",
      "track-progress"
    ],
    "triggers": [
      "certify",
      "get certificate",
      "show progress",
      "graduation"
    ],
    "dependencies": {
      "@clawford/assessment": ">=0.1.0"
    },
    "expectedImprovement": 30
  },
  {
    "slug": "chain-analyzer",
    "name": "@clawford/chain-analyzer",
    "description": "On-chain data analysis, address profiling, fund flow tracking, and whale behavior detection for OpenClaw Agent",
    "category": "crypto",
    "tags": [
      "crypto",
      "blockchain",
      "on-chain",
      "analytics",
      "whale-tracking",
      "fund-flow",
      "address-profiling",
      "defi",
      "etherscan",
      "dune"
    ],
    "capabilities": [
      "address-profiling",
      "fund-flow-tracing",
      "whale-detection",
      "token-holder-analysis",
      "transaction-graph-analysis",
      "smart-contract-interaction-analysis"
    ],
    "triggers": [
      "analyze address",
      "trace funds",
      "track whale",
      "on-chain analysis",
      "blockchain analysis",
      "fund flow",
      "who is this wallet",
      "token holders",
      "smart money",
      "chain analysis"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "code-gen",
    "name": "@clawford/code-gen",
    "description": "Complete code generation with proper architecture, error handling, type safety, and test accompaniment for OpenClaw Agent",
    "category": "code-assistance",
    "tags": [
      "code",
      "gen",
      "programming",
      "development",
      "complete",
      "generation",
      "proper"
    ],
    "capabilities": [
      "generate-code",
      "scaffold-project",
      "implement-algorithm"
    ],
    "triggers": [
      "write code",
      "generate function",
      "create API",
      "implement feature",
      "code this"
    ],
    "dependencies": {},
    "expectedImprovement": 50
  },
  {
    "slug": "code-review",
    "name": "@clawford/code-review",
    "description": "Systematic code review identifying security vulnerabilities, performance issues, and code smells with human-level coverage for OpenClaw Agent",
    "category": "code-assistance",
    "tags": [
      "code",
      "review",
      "programming",
      "development",
      "systematic",
      "identifying",
      "security"
    ],
    "capabilities": [
      "detect-issues",
      "suggest-improvements",
      "assess-quality"
    ],
    "triggers": [
      "review code",
      "code review",
      "check this code",
      "find bugs",
      "security audit",
      "review my code",
      "check for vulnerabilities",
      "code quality"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "content-engine",
    "name": "@clawford/content-engine",
    "description": "Multi-platform content creation and repurposing engine for AI agents",
    "category": "creative-generation",
    "tags": [
      "content",
      "social-media",
      "writing",
      "twitter",
      "linkedin",
      "repurposing"
    ],
    "capabilities": [
      "create-platform-native-content",
      "repurpose-content",
      "adapt-tone-per-platform"
    ],
    "triggers": [
      "write post",
      "create content",
      "social media",
      "tweet",
      "thread",
      "repurpose"
    ],
    "dependencies": {},
    "expectedImprovement": 40
  },
  {
    "slug": "copywriter",
    "name": "@clawford/copywriter",
    "description": "Marketing copywriting specialist that applies proven persuasion frameworks (AIDA, PAS, BAB) for audience-targeted copy with optimized CTAs and click-through rate improvement",
    "category": "creative-generation",
    "tags": [
      "copywriter",
      "creative",
      "generation",
      "writing",
      "marketing",
      "copywriting",
      "specialist"
    ],
    "capabilities": [
      "apply-persuasion-framework",
      "optimize-cta",
      "target-audience"
    ],
    "triggers": [
      "write copy",
      "marketing copy",
      "landing page",
      "ad copy",
      "CTA",
      "sales copy"
    ],
    "dependencies": {
      "@clawford/sentiment-analyzer": ">=0.1.0"
    },
    "expectedImprovement": 30
  },
  {
    "slug": "debugger",
    "name": "@clawford/debugger",
    "description": "Root cause analysis, bug diagnosis, and fix suggestion for OpenClaw Agent — improves debugging efficiency 5x with systematic hypothesis-driven investigation",
    "category": "code-assistance",
    "tags": [
      "debugger",
      "code",
      "programming",
      "development",
      "root",
      "cause",
      "analysis"
    ],
    "capabilities": [
      "diagnose-bugs",
      "root-cause-analysis",
      "suggest-fixes"
    ],
    "triggers": [
      "debug",
      "fix bug",
      "why is this failing",
      "error",
      "stack trace",
      "exception",
      "not working",
      "unexpected behavior",
      "crash",
      "broken"
    ],
    "dependencies": {
      "@clawford/code-review": ">=0.1.0"
    },
    "expectedImprovement": 500
  },
  {
    "slug": "dex-trader",
    "name": "@clawford/dex-trader",
    "description": "DEX trading strategy analysis, liquidity assessment, slippage optimization, and MEV-aware execution planning for OpenClaw Agent",
    "category": "crypto",
    "tags": [
      "crypto",
      "dex",
      "trading",
      "defi",
      "amm",
      "uniswap",
      "pancakeswap",
      "liquidity",
      "slippage",
      "mev",
      "swap"
    ],
    "capabilities": [
      "amm-analysis",
      "slippage-optimization",
      "liquidity-assessment",
      "mev-awareness",
      "trade-routing",
      "lp-strategy-analysis",
      "price-impact-estimation"
    ],
    "triggers": [
      "swap tokens",
      "dex trade",
      "liquidity pool",
      "slippage",
      "impermanent loss",
      "provide liquidity",
      "best swap route",
      "price impact",
      "mev protection",
      "dex strategy"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "doc-gen",
    "name": "@clawford/doc-gen",
    "description": "Automated documentation generation for APIs, READMEs, changelogs, and code-level docs — raising doc completeness from 30% to 90% for OpenClaw Agent",
    "category": "code-assistance",
    "tags": [
      "doc",
      "gen",
      "code",
      "programming",
      "development",
      "automated",
      "documentation",
      "generation"
    ],
    "capabilities": [
      "generate-api-docs",
      "create-readme",
      "write-changelogs"
    ],
    "triggers": [
      "generate docs",
      "document this",
      "write README",
      "API documentation",
      "changelog",
      "add JSDoc",
      "OpenAPI spec",
      "document the API",
      "write documentation"
    ],
    "dependencies": {
      "@clawford/code-gen": ">=0.1.0"
    },
    "expectedImprovement": 30
  },
  {
    "slug": "google-search",
    "name": "@clawford/google-search",
    "description": "Advanced Google search query construction, result filtering, and relevance ranking for OpenClaw Agent",
    "category": "information-retrieval",
    "tags": [
      "google",
      "search",
      "retrieval",
      "information",
      "advanced",
      "query",
      "construction"
    ],
    "capabilities": [
      "construct-search-query",
      "rank-results",
      "extract-snippets"
    ],
    "triggers": [
      "search for",
      "find information",
      "look up",
      "google",
      "search the web",
      "find sources"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "healthcheck",
    "name": "@clawford/healthcheck",
    "description": "Agent health inspection across hardware, config, security, skills, and autonomy",
    "category": "meta",
    "tags": [
      "health",
      "diagnostics",
      "audit",
      "config",
      "security"
    ],
    "capabilities": [
      "system-health-check",
      "config-audit",
      "security-scan",
      "skill-inventory"
    ],
    "triggers": [
      "health check",
      "diagnose",
      "audit",
      "system status",
      "am I healthy"
    ],
    "dependencies": {},
    "expectedImprovement": 25
  },
  {
    "slug": "keyword-extractor",
    "name": "@clawford/keyword-extractor",
    "description": "Semantic-level keyword extraction, topic clustering, and domain-aware term ranking for OpenClaw Agent",
    "category": "content-processing",
    "tags": [
      "keyword",
      "extractor",
      "content",
      "processing",
      "nlp",
      "semantic-level",
      "extraction",
      "topic"
    ],
    "capabilities": [
      "extract-keywords",
      "identify-topics",
      "compute-relevance"
    ],
    "triggers": [
      "extract keywords",
      "key terms",
      "topic extraction",
      "keyword analysis",
      "find keywords",
      "identify topics",
      "extract key phrases"
    ],
    "dependencies": {},
    "expectedImprovement": 40
  },
  {
    "slug": "kol-manager",
    "name": "@clawford/kol-manager",
    "description": "KOL operations management, influence analysis, and collaboration strategy for crypto projects — campaign planning, authenticity vetting, and ROI measurement",
    "category": "crypto",
    "tags": [
      "kol",
      "influencer",
      "crypto-marketing",
      "campaign-management",
      "roi-analysis",
      "fake-detection",
      "collaboration",
      "twitter-spaces",
      "telegram",
      "youtube"
    ],
    "capabilities": [
      "plan-kol-campaign",
      "vet-kol-authenticity",
      "analyze-influence-metrics",
      "negotiate-collaboration-terms",
      "measure-campaign-roi",
      "detect-fake-followers",
      "track-deliverables"
    ],
    "triggers": [
      "kol campaign",
      "influencer marketing",
      "find kol",
      "vet influencer",
      "kol strategy",
      "crypto marketing",
      "shill campaign",
      "twitter spaces",
      "kol pricing",
      "influencer roi"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "mental-models",
    "name": "@clawford/mental-models",
    "description": "A latticework thinking advisor built on Charlie Munger's mental models framework — activates on genuine judgment calls with 24 disciplinary lenses, convergence detection, and personalized blind-spot analysis",
    "category": "reasoning",
    "tags": [
      "mental-models",
      "reasoning",
      "decision-making",
      "munger",
      "latticework",
      "judgment",
      "thinking",
      "frameworks"
    ],
    "capabilities": [
      "latticework-analysis",
      "thinking-diagnostic",
      "blind-spot-detection"
    ],
    "triggers": [
      "should I",
      "is this worth it",
      "which option",
      "what's really going on",
      "diagnose my thinking",
      "blind spots",
      "how should I decide",
      "judgment call",
      "mental model",
      "latticework"
    ],
    "dependencies": {},
    "expectedImprovement": 50
  },
  {
    "slug": "reddit-tracker",
    "name": "@clawford/reddit-tracker",
    "description": "Reddit community monitoring, engagement velocity tracking, cross-subreddit correlation, and early trend detection for OpenClaw Agent",
    "category": "information-retrieval",
    "tags": [
      "reddit",
      "tracker",
      "search",
      "retrieval",
      "information",
      "community",
      "monitoring",
      "engagement"
    ],
    "capabilities": [
      "track-subreddits",
      "detect-trending-posts",
      "extract-discussions"
    ],
    "triggers": [
      "reddit",
      "subreddit",
      "trending",
      "community",
      "hotspot",
      "reddit trends",
      "what's hot on reddit"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "refactor",
    "name": "@clawford/refactor",
    "description": "Automated code refactoring with design pattern application, complexity reduction, and behavioral equivalence verification for OpenClaw Agent",
    "category": "code-assistance",
    "tags": [
      "refactor",
      "code",
      "programming",
      "development",
      "automated",
      "refactoring",
      "design"
    ],
    "capabilities": [
      "apply-patterns",
      "reduce-complexity",
      "verify-equivalence"
    ],
    "triggers": [
      "refactor",
      "clean up code",
      "improve code quality",
      "apply design pattern",
      "reduce complexity",
      "simplify code",
      "restructure code",
      "reduce duplication"
    ],
    "dependencies": {
      "@clawford/code-review": ">=0.1.0"
    },
    "expectedImprovement": 40
  },
  {
    "slug": "reminder",
    "name": "@clawford/reminder",
    "description": "BotLearn 7-Step Quickstart Tutorial Reminder — heartbeat-driven reminders every 24 hours that dynamically fetch and summarize botlearn.ai quickstart pages, track progress, and present tips in the user's own language",
    "category": "information-retrieval",
    "tags": [
      "botlearn",
      "tutorial",
      "learning",
      "heartbeat",
      "daily-reminder",
      "quickstart",
      "7-day",
      "onboarding",
      "progress-tracking",
      "chinese"
    ],
    "capabilities": [
      "heartbeat-driven",
      "daily-reminder",
      "dynamic-page-fetch",
      "progress-tracking",
      "chinese-summarization",
      "offline-fallback",
      "non-intrusive"
    ],
    "triggers": [
      "botlearn教程",
      "quickstart",
      "今日提醒",
      "学习进度",
      "botlearn tips",
      "7天教程",
      "tutorial reminder",
      "每日学习"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "rewriter",
    "name": "@clawford/rewriter",
    "description": "Style transformation, audience adaptation, and natural content rewriting with factual accuracy preservation for OpenClaw Agent",
    "category": "content-processing",
    "tags": [
      "rewriter",
      "content",
      "processing",
      "nlp",
      "style",
      "transformation",
      "audience"
    ],
    "capabilities": [
      "transform-style",
      "adapt-audience",
      "preserve-facts"
    ],
    "triggers": [
      "rewrite",
      "rephrase",
      "paraphrase",
      "reword",
      "adapt for audience"
    ],
    "dependencies": {
      "@clawford/summarizer": ">=0.1.0"
    },
    "expectedImprovement": 35
  },
  {
    "slug": "rss-manager",
    "name": "@clawford/rss-manager",
    "description": "Multi-source RSS/Atom feed aggregation, deduplication, importance scoring, topic clustering, and daily digest generation for OpenClaw Agent",
    "category": "information-retrieval",
    "tags": [
      "rss",
      "manager",
      "search",
      "retrieval",
      "information",
      "multi-source",
      "rssatom",
      "feed"
    ],
    "capabilities": [
      "discover-feeds",
      "aggregate-content",
      "filter-updates"
    ],
    "triggers": [
      "rss",
      "feed",
      "subscribe",
      "digest",
      "news feed",
      "aggregator",
      "syndication",
      "feed reader"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "selfoptimize",
    "name": "@clawford/selfoptimize",
    "description": "Self-improvement through error logging, pattern detection, and learning extraction",
    "category": "meta",
    "tags": [
      "self-improvement",
      "learning",
      "error-detection",
      "optimization"
    ],
    "capabilities": [
      "error-logging",
      "pattern-detection",
      "learning-extraction",
      "memory-promotion"
    ],
    "triggers": [
      "optimize",
      "improve",
      "learn from mistakes",
      "self improve",
      "get better"
    ],
    "dependencies": {},
    "expectedImprovement": 40
  },
  {
    "slug": "sentiment-analyzer",
    "name": "@clawford/sentiment-analyzer",
    "description": "Fine-grained sentiment recognition and opinion mining with aspect-based analysis, sarcasm detection, and polarity classification for OpenClaw Agent",
    "category": "content-processing",
    "tags": [
      "sentiment",
      "analyzer",
      "content",
      "processing",
      "nlp",
      "fine-grained",
      "recognition",
      "opinion"
    ],
    "capabilities": [
      "detect-sentiment",
      "analyze-emotion",
      "score-polarity"
    ],
    "triggers": [
      "sentiment",
      "opinion mining",
      "analyze tone",
      "polarity",
      "sentiment analysis",
      "emotional tone",
      "opinion detection",
      "feeling analysis"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "social-media",
    "name": "@clawford/social-media",
    "description": "Platform-adapted social media content creation with optimal hashtags, timing, and engagement optimization for OpenClaw Agent",
    "category": "creative-generation",
    "tags": [
      "social",
      "media",
      "creative",
      "generation",
      "writing",
      "platform-adapted",
      "content",
      "creation"
    ],
    "capabilities": [
      "adapt-platform-format",
      "optimize-hashtags",
      "schedule-timing"
    ],
    "triggers": [
      "social media post",
      "tweet",
      "LinkedIn post",
      "Instagram caption",
      "TikTok script",
      "create a post",
      "social content",
      "post for"
    ],
    "dependencies": {
      "@clawford/copywriter": ">=0.1.0"
    },
    "expectedImprovement": 30
  },
  {
    "slug": "storyteller",
    "name": "@clawford/storyteller",
    "description": "Crafts compelling stories with narrative structure, character development, and emotional rhythm for OpenClaw Agent",
    "category": "creative-generation",
    "tags": [
      "storyteller",
      "creative",
      "generation",
      "writing",
      "crafts",
      "compelling",
      "stories"
    ],
    "capabilities": [
      "craft-narrative",
      "develop-characters",
      "build-plot"
    ],
    "triggers": [
      "write a story",
      "tell a story",
      "create a narrative",
      "fiction",
      "storytelling"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "summarizer",
    "name": "@clawford/summarizer",
    "description": "Content summarization with core argument extraction, key detail retention, and accuracy self-checking for OpenClaw Agent",
    "category": "content-processing",
    "tags": [
      "summarizer",
      "content",
      "processing",
      "nlp",
      "summarization",
      "core",
      "argument"
    ],
    "capabilities": [
      "extract-key-points",
      "compress-content",
      "multi-doc-synthesis"
    ],
    "triggers": [
      "summarize",
      "summary",
      "key points",
      "TLDR",
      "digest",
      "main ideas",
      "boil down"
    ],
    "dependencies": {},
    "expectedImprovement": 45
  },
  {
    "slug": "token-launcher",
    "name": "@clawford/token-launcher",
    "description": "Token creation planning, smart contract security analysis, tokenomics design, and liquidity bootstrapping strategy for OpenClaw Agent",
    "category": "crypto",
    "tags": [
      "crypto",
      "token",
      "launch",
      "erc20",
      "bep20",
      "tokenomics",
      "smart-contract",
      "liquidity",
      "vesting",
      "fair-launch",
      "security"
    ],
    "capabilities": [
      "tokenomics-design",
      "contract-security-analysis",
      "launch-strategy-planning",
      "liquidity-bootstrapping",
      "vesting-schedule-design",
      "rugpull-detection"
    ],
    "triggers": [
      "create token",
      "launch token",
      "tokenomics",
      "token design",
      "vesting schedule",
      "liquidity lock",
      "fair launch",
      "token audit",
      "deploy token",
      "token security"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "translator",
    "name": "@clawford/translator",
    "description": "Context-aware, human-level translation with terminology consistency, register adaptation, and cultural localization for OpenClaw Agent",
    "category": "content-processing",
    "tags": [
      "translator",
      "content",
      "processing",
      "nlp",
      "context-aware",
      "human-level",
      "translation"
    ],
    "capabilities": [
      "detect-language",
      "translate-text",
      "preserve-tone"
    ],
    "triggers": [
      "translate",
      "translation",
      "翻译",
      "convert to [language]",
      "say this in",
      "how do you say",
      "localize"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "twitter-intel",
    "name": "@clawford/twitter-intel",
    "description": "Twitter/X platform intelligence gathering — tracking KOLs, extracting trending topics, analyzing engagement signals, detecting bot activity, and synthesizing actionable insights for OpenClaw Agent",
    "category": "information-retrieval",
    "tags": [
      "twitter",
      "intel",
      "search",
      "retrieval",
      "information",
      "twitterx",
      "platform",
      "intelligence"
    ],
    "capabilities": [
      "monitor-trends",
      "extract-thread-context",
      "sentiment-tracking"
    ],
    "triggers": [
      "twitter",
      "tweet",
      "KOL",
      "trending",
      "X platform",
      "twitter intelligence",
      "twitter analysis",
      "influencer tracking",
      "twitter trends",
      "social listening"
    ],
    "dependencies": {},
    "expectedImprovement": 30
  },
  {
    "slug": "wallet-monitor",
    "name": "@clawford/wallet-monitor",
    "description": "Wallet monitoring, whale tracking, transaction anomaly detection, and cross-chain alerting for crypto operations and security",
    "category": "crypto",
    "tags": [
      "wallet",
      "whale-tracking",
      "on-chain-analysis",
      "transaction-monitoring",
      "anomaly-detection",
      "cross-chain",
      "alerts",
      "smart-money",
      "security",
      "portfolio-tracking"
    ],
    "capabilities": [
      "monitor-wallet-activity",
      "track-whale-movements",
      "detect-anomalous-transactions",
      "label-wallet-entities",
      "configure-alert-rules",
      "analyze-token-approvals",
      "score-wallet-security",
      "track-cross-chain-flows"
    ],
    "triggers": [
      "monitor wallet",
      "track whale",
      "watch address",
      "wallet alert",
      "whale movement",
      "suspicious transaction",
      "on-chain monitoring",
      "smart money tracking",
      "token approval risk",
      "wallet security"
    ],
    "dependencies": {},
    "expectedImprovement": 35
  },
  {
    "slug": "writer",
    "name": "@clawford/writer",
    "description": "Structured article writing with evidence-based argumentation, consistent style, and quality improvement of 60% for OpenClaw Agent",
    "category": "creative-generation",
    "tags": [
      "writer",
      "creative",
      "generation",
      "writing",
      "structured",
      "article",
      "evidence-based"
    ],
    "capabilities": [
      "structure-article",
      "evidence-argumentation",
      "style-consistency"
    ],
    "triggers": [
      "write an article",
      "write about",
      "compose",
      "draft article",
      "blog post"
    ],
    "dependencies": {
      "@clawford/summarizer": ">=0.1.0",
      "@clawford/keyword-extractor": ">=0.1.0"
    },
    "expectedImprovement": 60
  }
] as const;
